import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsDateString, IsNotEmpty } from 'class-validator';

export class CreateActualFpprDto {
  @ApiProperty({
    description: 'FPPR Number',
    example: 'JAT/CP/2024/01/000001',
  })
  @IsString()
  @IsNotEmpty()
  FPPR_NUMBER: string;

  @ApiProperty({
    description: 'Actual Date',
    example: '2024-01-01',
  })
  @IsDateString()
  @IsNotEmpty()
  ACTUAL_DATE: string;

  @ApiProperty({
    description: 'Actual Status',
    example: 'DEPARTURE',
  })
  @IsString()
  @IsNotEmpty()
  ACTUAL_STATUS: string;

  @ApiProperty({
    description: 'Source System',
    example: 'DMS',
  })
  @IsString()
  @IsNotEmpty()
  SOURCE_SYSTEM: string;

  @ApiProperty({
    description: 'Source Batch ID',
    example: '1234567890',
  })
  @IsString()
  @IsNotEmpty()
  SOURCE_BATCH_ID: string;

  @ApiProperty({
    description: 'Source Header ID',
    example: '1234567890',
  })
  @IsString()
  @IsNotEmpty()
  SOURCE_HEADER_ID: string;

  @ApiProperty({
    description: 'Source Line ID',
    example: '1234567890',
  })
  @IsString()
  @IsNotEmpty()
  SOURCE_LINE_ID: string;

  @ApiProperty({
    description: 'Organization ID',
    example: 100,
    required: false,
  })
  ORGANIZATION_ID?: number;

  @ApiProperty({
    description: 'Organization ID (alternative)',
    example: 100,
    required: false,
  })
  ORG_ID?: number;

  @ApiProperty({
    description: 'Description',
    example: 'Sample description',
    required: false,
  })
  DESCRIPTION?: string;

  @ApiProperty({
    description: 'Attribute Category',
    example: 'CATEGORY1',
    required: false,
  })
  ATTRIBUTE_CATEGORY?: string;

  @ApiProperty({
    description: 'Attribute 1',
    example: 'Value 1',
    required: false,
  })
  ATTRIBUTE1?: string;

  @ApiProperty({
    description: 'Attribute 2',
    example: 'Value 2',
    required: false,
  })
  ATTRIBUTE2?: string;

  @ApiProperty({
    description: 'Attribute 3',
    example: 'Value 3',
    required: false,
  })
  ATTRIBUTE3?: string;

  @ApiProperty({
    description: 'Attribute 4',
    example: 'Value 4',
    required: false,
  })
  ATTRIBUTE4?: string;

  @ApiProperty({
    description: 'Attribute 5',
    example: 'Value 5',
    required: false,
  })
  ATTRIBUTE5?: string;

  @ApiProperty({
    description: 'Attribute 6',
    example: 'Value 6',
    required: false,
  })
  ATTRIBUTE6?: string;

  @ApiProperty({
    description: 'Attribute 7',
    example: 'Value 7',
    required: false,
  })
  ATTRIBUTE7?: string;

  @ApiProperty({
    description: 'Attribute 8',
    example: 'Value 8',
    required: false,
  })
  ATTRIBUTE8?: string;

  @ApiProperty({
    description: 'Attribute 9',
    example: 'Value 9',
    required: false,
  })
  ATTRIBUTE9?: string;

  @ApiProperty({
    description: 'Attribute 10',
    example: 'Value 10',
    required: false,
  })
  ATTRIBUTE10?: string;

  @ApiProperty({
    description: 'Attribute 11',
    example: 'Value 11',
    required: false,
  })
  ATTRIBUTE11?: string;

  @ApiProperty({
    description: 'Attribute 12',
    example: 'Value 12',
    required: false,
  })
  ATTRIBUTE12?: string;

  @ApiProperty({
    description: 'Attribute 13',
    example: 'Value 13',
    required: false,
  })
  ATTRIBUTE13?: string;

  @ApiProperty({
    description: 'Attribute 14',
    example: 'Value 14',
    required: false,
  })
  ATTRIBUTE14?: string;

  @ApiProperty({
    description: 'Attribute 15',
    example: 'Value 15',
    required: false,
  })
  ATTRIBUTE15?: string;

  @ApiProperty({
    description: 'Request ID',
    example: 98765,
    required: false,
  })
  REQUEST_ID?: number;

  @ApiProperty({
    description: 'Last Update Login',
    example: 12345,
    required: false,
  })
  LAST_UPDATE_LOGIN?: number;
}

export class ActualFpprResponseDto {
  @ApiProperty({
    description: 'Actual ID (autogenerated)',
    example: 12345,
  })
  ACTUAL_ID: number;

  @ApiProperty({
    description: 'FPPR Number',
    example: 'JAT/CP/2024/01/000001',
  })
  FPPR_NUMBER: string;

  @ApiProperty({
    description: 'Actual Date',
    example: '2024-01-01',
  })
  ACTUAL_DATE: Date;

  @ApiProperty({
    description: 'Actual Status',
    example: 'DEPARTURE',
  })
  ACTUAL_STATUS: string;

  @ApiProperty({
    description: 'Source System',
    example: 'DMS',
  })
  SOURCE_SYSTEM: string;

  @ApiProperty({
    description: 'Source Batch ID',
    example: '1234567890',
  })
  SOURCE_BATCH_ID: string;

  @ApiProperty({
    description: 'Source Header ID',
    example: '1234567890',
  })
  SOURCE_HEADER_ID: string;

  @ApiProperty({
    description: 'Source Line ID',
    example: '1234567890',
  })
  SOURCE_LINE_ID: string;

  @ApiProperty({
    description: 'Organization ID',
    example: 100,
  })
  ORGANIZATION_ID: number;

  @ApiProperty({
    description: 'Organization ID (alternative)',
    example: 100,
  })
  ORG_ID: number;

  @ApiProperty({
    description: 'Description',
    example: 'Sample description',
  })
  DESCRIPTION: string;

  @ApiProperty({
    description: 'Attribute Category',
    example: 'CATEGORY1',
  })
  ATTRIBUTE_CATEGORY: string;

  @ApiProperty({
    description: 'Attribute 1',
    example: 'Value 1',
  })
  ATTRIBUTE1: string;

  @ApiProperty({
    description: 'Attribute 2',
    example: 'Value 2',
  })
  ATTRIBUTE2: string;

  @ApiProperty({
    description: 'Attribute 3',
    example: 'Value 3',
  })
  ATTRIBUTE3: string;

  @ApiProperty({
    description: 'Attribute 4',
    example: 'Value 4',
  })
  ATTRIBUTE4: string;

  @ApiProperty({
    description: 'Attribute 5',
    example: 'Value 5',
  })
  ATTRIBUTE5: string;

  @ApiProperty({
    description: 'Attribute 6',
    example: 'Value 6',
  })
  ATTRIBUTE6: string;

  @ApiProperty({
    description: 'Attribute 7',
    example: 'Value 7',
  })
  ATTRIBUTE7: string;

  @ApiProperty({
    description: 'Attribute 8',
    example: 'Value 8',
  })
  ATTRIBUTE8: string;

  @ApiProperty({
    description: 'Attribute 9',
    example: 'Value 9',
  })
  ATTRIBUTE9: string;

  @ApiProperty({
    description: 'Attribute 10',
    example: 'Value 10',
  })
  ATTRIBUTE10: string;

  @ApiProperty({
    description: 'Attribute 11',
    example: 'Value 11',
  })
  ATTRIBUTE11: string;

  @ApiProperty({
    description: 'Attribute 12',
    example: 'Value 12',
  })
  ATTRIBUTE12: string;

  @ApiProperty({
    description: 'Attribute 13',
    example: 'Value 13',
  })
  ATTRIBUTE13: string;

  @ApiProperty({
    description: 'Attribute 14',
    example: 'Value 14',
  })
  ATTRIBUTE14: string;

  @ApiProperty({
    description: 'Attribute 15',
    example: 'Value 15',
  })
  ATTRIBUTE15: string;

  @ApiProperty({
    description: 'Request ID',
    example: 98765,
  })
  REQUEST_ID: number;

  @ApiProperty({
    description: 'Creation Date',
    example: '2023-11-27T00:00:00.000Z',
  })
  CREATION_DATE: Date;

  @ApiProperty({
    description: 'Created By',
    example: 1234,
  })
  CREATED_BY: number;

  @ApiProperty({
    description: 'Last Update Date',
    example: '2023-11-27T00:00:00.000Z',
  })
  LAST_UPDATE_DATE: Date;

  @ApiProperty({
    description: 'Last Updated By',
    example: 1234,
  })
  LAST_UPDATED_BY: number;

  @ApiProperty({
    description: 'Last Update Login',
    example: 12345,
  })
  LAST_UPDATE_LOGIN: number;
}
