import { registerAs } from '@nestjs/config';

export default registerAs(
  'rmq',
  (): Record<string, any> => ({
    uri: process.env.RABBITMQ_URL,
    auth: process.env.RABBITMQ_AUTH_QUEUE,
    customer: process.env.RABBITMQ_CUSTOMER_QUEUE,
    branch: process.env.RABBITMQ_BRANCH_QUEUE,
    region: process.env.RABBITMQ_REGION_QUEUE,
    employee: process.env.RABBITMQ_EMPLOYEE_QUEUE,
    geotree: process.env.RABBITMQ_GEOTREE_QUEUE,
    salesOrder: process.env.RABBITMQ_SALES_ORDER_QUEUE,
    purchaseOrder: process.env.RABBITMQ_PURCHASE_ORDER_QUEUE,
    warehouse: process.env.RABBITMQ_WAREHOUSE_QUEUE,
    salesItem: process.env.RABBITMQ_SALES_ITEM_QUEUE,
    salesman: process.env.RABBITMQ_SALESMAN_QUEUE,
    province: process.env.RABBITMQ_PROVINCE_QUEUE,
    city: process.env.RABBITMQ_CITY_QUEUE,
    district: process.env.RABBITMQ_DISTRICT_QUEUE,
    subDistrict: process.env.RABBITMQ_SUB_DISTRICT_QUEUE,
    organization: process.env.RABBITMQ_ORGANIZATION_QUEUE,
    position: process.env.RABBITMQ_POSITION_QUEUE,
    supplier: process.env.RABBITMQ_SUPPLIER_QUEUE,
    salesItemConversion: process.env.RABBITMQ_SALES_ITEM_CONVERSION_QUEUE,
    receiptMethod: process.env.RABBITMQ_RECEIPT_METHOD_QUEUE,
    salesActivity: process.env.RABBITMQ_SALES_ACTIVITY_QUEUE,
    userDms: process.env.RABBITMQ_USER_DMS_QUEUE,
    priceList: process.env.RABBITMQ_PRICE_LIST_QUEUE,
    itemList: process.env.RABBITMQ_ITEM_LIST_QUEUE,
  }),
);
